package com.jira2.validator.response;

import com.fasterxml.jackson.annotation.JsonInclude;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.util.ArrayList;
import java.util.List;

@Data
@JsonInclude(JsonInclude.Include.NON_NULL)
public class Fields
{
    private String customfield_11800;
    private String customfield_11002;
    private String customfield_12301;
    private List<Object> components = new ArrayList<Object>();
    private List<Object> subtasks = new ArrayList<Object>();
    private List<String> customfield_14802;
    private Issuetype issuetype;
    private String description;
    private String summary;
    private String duedate = null;
    private String timeestimate = null;
    private List<Object> versions = new ArrayList<Object>();
    private JiraStatus status;
    private String archiveddate = null;
    private String aggregatetimeestimate = null;
    private float timespent;
    private float aggregatetimespent;
    private float workratio;
    private String created;
    private List<Object> attachment;
    private String customfield_19200;
    private String customfield_23700 = null;
    private String customfield_19201 = null;
    private String customfield_19202 = null;
    private String customfield_19203 = null;
    private String customfield_13100 = null;
    private String customfield_17700 = null;
    private String customfield_13101 = null;
    private String customfield_17704 = null;
    private Object customfield_17703 = null;
    private String customfield_17701 = null;
    private String customfield_10500 = null;
    private String customfield_22600 = null;
    private String lastViewed;
    private Object customfield_18900 = null;
    private String customfield_18901 = null;
    private Object customfield_20323 = null;
    private Object customfield_20327 = null;
    List<String> labels = new ArrayList<>();
    private String aggregatetimeoriginalestimate = null;
    List<Object> issuelinks = new ArrayList<Object>();
    Assignee assignee;
    private String customfield_23600 = null;
    private String customfield_23601 = null;
    private String customfield_19300 = null;
    private String customfield_23602 = null;
    private String customfield_19301 = null;
    private String customfield_23603 = null;
    private String customfield_19302 = null;
    private String customfield_23604 = null;
    private String customfield_17003 = null;
    private String customfield_23605 = null;
    private String customfield_17002 = null;
    private String customfield_23606 = null;
    private String customfield_17001 = null;
    private String customfield_23607 = null;
    private String customfield_23000 = null;
    private String customfield_17000 = null;
    private String customfield_19303 = null;
    private String customfield_17800 = null;
    private String customfield_10600 = null;
    private String customfield_22700 = null;
    private String customfield_18200 = null;
    private String customfield_14400 = null;
    private String archivedby = null;
    private String customfield_23500 = null;
    private String customfield_23501 = null;
    private String customfield_23502 = null;
    private String customfield_23503 = null;
    private String customfield_23504 = null;
    private String customfield_23505 = null;
    private String customfield_17102 = null;
    private String customfield_23506 = null;
    private String customfield_17101 = null;
    private String customfield_23507 = null;
    private String customfield_23508 = null;
    private String customfield_23509 = null;
    private String customfield_11000 = null;
    private String customfield_11003;
    private String customfield_10700 = null;
    private String customfield_10701 = null;
    private Object customfield_10703 = null;
    private Object customfield_10704 = null;
    private String customfield_23510 = null;
    private String customfield_22800;
    private String customfield_23511 = null;
    private String customfield_23512 = null;
    private String customfield_23513 = null;
    private String customfield_23514 = null;
    private String customfield_23515 = null;
    private String customfield_18301 = null;
    private String customfield_23516 = null;
    private String customfield_23517 = null;
    private String customfield_23518 = null;
    private String customfield_22000;
    private String customfield_23519 = null;
    private String customfield_18302 = null;
    private String customfield_18303 = null;
    private Object customfield_14500 = null;
    private String customfield_14501 = null;
    private String customfield_10016 = null;
    private String customfield_11900 = null;
    private float customfield_21702;
    private String customfield_23520 = null;
    private String updated;
    private String customfield_19500 = null;
    private String customfield_17201 = null;
    private String customfield_17200 = null;
    private String timeoriginalestimate = null;
    private String customfield_10010 = null;
    private String customfield_17202 = null;
    private Object customfield_10011 = null;
    private String customfield_13401 = null;
    private String customfield_10012 = null;
    private String customfield_19501 = null;
    private String customfield_13400 = null;
    private String customfield_10013 = null;
    private String customfield_10014 = null;
    private String customfield_19503 = null;
    private String customfield_13402 = null;
    private String customfield_19504 = null;
    private String customfield_10005 = null;
    private String customfield_10006 = null;
    private String customfield_10007 = null;
    private String customfield_10008 = null;
    private String customfield_10009 = null;
    private String customfield_20600;
    private String customfield_22900;
    private String customfield_18400 = null;
    private String customfield_22101 = null;
    private String customfield_22100 = null;
    private String customfield_10000 = null;
    private Object customfield_10001 = null;
    private String customfield_14601 = null;
    private String customfield_10003 = null;
    private String customfield_10004 = null;
    private String environment = null;
    private String customfield_21800 = null;
    private String customfield_21000 = null;
    private String customfield_17302 = null;
    List<Object> fixVersions = new ArrayList<Object>();
    private String customfield_11200;
    private String customfield_10901 = null;
    private String customfield_16321 = null;
    private Object customfield_16200 = null;
    private String customfield_16320 = null;
    private String customfield_16325 = null;
    private String customfield_18504 = null;
    private String customfield_16324 = null;
    private String customfield_16323 = null;
    private float customfield_16202;
    private String customfield_16322 = null;
    private String customfield_16201 = null;
    private String customfield_10100 = null;
    private String customfield_14700 = null;
    private String customfield_16328 = null;
    private String customfield_16327 = null;
    private String customfield_16326 = null;
    private Object customfield_14812 = null;
    private String customfield_14813;
    private String customfield_16319 = null;
    List<Object> customfield_21900 = new ArrayList<Object>();
    private String customfield_21100 = null;
    private String customfield_16310 = null;
    private String customfield_16314 = null;
    private String customfield_16312 = null;
    private String customfield_16311 = null;
    private String customfield_16318 = null;
    private String customfield_16317 = null;
    private String customfield_19700;
    private String customfield_16316 = null;
    private String customfield_16315 = null;
    private String customfield_14803;
    private String customfield_10205;
    private String customfield_16309 = null;
    List<Object> customfield_14801 = new ArrayList<Object>();
    private String customfield_16308 = null;
    private String customfield_10206 = null;
    private Object customfield_10208 = null;
    private String customfield_22302 = null;
    private String customfield_22301 = null;
    private String customfield_20000 = null;
    private String customfield_22300 = null;
    private String customfield_14000;
    private String customfield_16307 = null;
    List<Object> customfield_14800 = new ArrayList<Object>();
    private String customfield_10202 = null;
    private String customfield_14913 = null;
    private String customfield_14914 = null;
    private String customfield_14911 = null;
    private String customfield_14912 = null;
    private String customfield_14917 = null;
    private String customfield_14918 = null;
    private String customfield_14915 = null;
    private String customfield_14916 = null;
    private String customfield_19002 = null;
    private String customfield_19802 = null;
    private String customfield_15200 = null;
    private String customfield_17500 = null;
    private String customfield_19804 = null;
    private String customfield_19805 = null;
    private String customfield_14910 = null;
    private String customfield_10311 = null;
    private String customfield_19800 = null;
    private String customfield_14901 = null;
    private String customfield_17617 = null;
    private String customfield_10306 = null;
    private String customfield_14907 = null;
    private String customfield_10307 = null;
    private String customfield_10308 = null;
    private Object customfield_10309 = null;
    private String customfield_14908 = null;
    private String customfield_14909 = null;
    private String customfield_20900;
    private String customfield_22402 = null;
    private String customfield_22401 = null;
    private String customfield_22400 = null;
    private String customfield_17612 = null;
    private String customfield_17616 = null;
    private String customfield_17615 = null;
    private String customfield_10300 = null;
    private String customfield_17614 = null;
    private String customfield_18700 = null;
    private String customfield_17613;
    private String customfield_17609 = null;
    private String customfield_17608 = null;
    private String customfield_17606 = null;
    private String customfield_23800 = null;
    private String customfield_17601 = null;
    private String customfield_17600 = null;
    private String customfield_15300 = null;
    private String customfield_17605 = null;
    private String customfield_17604 = null;
    private String customfield_17603 = null;
    private String customfield_17602 = null;
    private String customfield_12703 = null;
    private String customfield_22503 = null;
    private String customfield_22502 = null;
    private String customfield_22501 = null;
    private String customfield_18001;
    private String customfield_22500 = null;
    private List<String> customfield_18000 = new ArrayList<>();
    private String customfield_10400 = null;
    private String customfield_20336;
    private String customfield_20332;
    private Object customfield_20320;
    private String customfield_20322;
    private Object customfield_20328;
    private String customfield_20324;
    private String customfield_20326;
    private String customfield_20030;
    private String customfield_20340;
    private String customfield_20342;
    private Object customfield_20350;
}
